title: 'Remaining Days of PDuts (as the President) &mdash; DEV'
description: "Let's count Pduts's remaining days as President, together."
url: 'https://remainingdaysofpduts.marcreyes.xyz'
color: '#324ab2'
twitter: '@marcxplanet'