name: Remaining Days of PDuts 
on:
  schedule:
    - cron: '40 0 * * *'
jobs:
  remaining-days-of-pduts:
    runs-on: ubuntu-latest
    steps:
    - name: ⏰ Set timezone of runner to Asia/Manila
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Manila"
        timezoneMacos: "Asia/Manila"
        timezoneWindows: "Manila Standard Time"
    - uses: actions/checkout@v2
    - name: 🛠️ Install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: ⚙️ Generate image of PDuts's remaining days as of today
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: https://remainingdaysofpduts.marcreyes.xyz
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: ⬆️ Uploading artifacts from runner to staging
    - name: 📁 Prepare screenshots for commit
      run: |
        rm -rf images/today.jpg 
        ls screenshots | grep 'desktopPage1920x1080' | xargs -I{} mv screenshots/{} images/today.jpg
    - name: ⌛ Remaining days of PDuts as of today 
      uses: swinton/commit@v2.x
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          images/today.jpg
        commit-message: ⌛ Remaining days of PDuts as of today
        ref: refs/heads/main

